### ISSUE TITLE
[FE] Create view profile

### ISSUE THREAD

**Issue by jacque1ine** [jacque1ine/technova-2023#3]
Properties:

- Picture 
- Pronouns
- location
- Role: User Vs Company 
- Name 
- Tags 
- Bio 
- Points 
- Level/badge 
- Linkedin

**Comment by lorena-rosati** [comment]
Tags: 

Racial minorities - specify??
LGBTQ+
Immigrant
Post-secondary student
High school student
Post-grad
Industry - specify?? maybe tags by science, tech, eng, math
